
## file_path, be careful, all would be in .xlsx  (please put your file in the input folder)


#############################  the parameters in the input file  #######################################  
input_file: intput/amazon_de_url.xlsx

input_sku_name_col: item_sku_name_de # the language is better to be consistent with the web region
country: de    # general country code (uk, fr, de, nl, ...); each search engine maps it internally
output_file: result.xlsx



#############################   declare the web, mandatory when use_match is  0   #########################
web: amazon.de

##############################   the parameters for the search  ##########################################
serper_max_calls: 2 






