
## file_path, be careful, all would be in .xlsx  (please put your file in the input folder)


#############################  the parameters in the input file  #######################################  
input_file: amazon_de_url.xlsx
input_sku_name_col: item_sku_name_de # the language is better to be consistent with the web region
country: de    # uk fr de nl ... the country code of the web, refer to serper




output_file: result.xlsx



## whether to use match algo (semantic match on the sku-category, and category-target web)
use_match: 0   # 0 for no, 1 for yes

#############################   declare the web, mandatory when use_match is  0   #########################
web: amazon.de







