from __future__ import annotations

from collections.abc import Sequence
import sqlite3
from pathlib import Path
from typing import Optional

_DDL = """
-- Versioned parser implementations generated or seeded for each retailer.
CREATE TABLE IF NOT EXISTS parsers (
    id INTEGER PRIMARY KEY AUTOINCREMENT, -- Surrogate parser identifier; referenced by scrape_runs.winning_parser_id
    site TEXT NOT NULL, -- Retailer key such as tesco, argos, or amazon
    version TEXT NOT NULL, -- Parser version label supplied when the parser is created
    code TEXT NOT NULL, -- Executable Python parser source stored as text
    page_type_scope TEXT, -- Optional page-type specialization; currently not populated by runtime flows
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'retired')), -- Lifecycle state: active or retired
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')), -- UTC creation timestamp generated by SQLite
    created_by TEXT NOT NULL DEFAULT 'initial' CHECK(created_by IN ('initial', 'agent')) -- Provenance: initial seed or repair agent
);

-- Golden HTML captures and expected outputs used to qualify parser promotion.
CREATE TABLE IF NOT EXISTS golden_samples (
    id INTEGER PRIMARY KEY AUTOINCREMENT, -- Surrogate golden-sample identifier
    site TEXT NOT NULL, -- Retailer partition key
    -- Declared scenario bucket covered by this sample.
    page_type TEXT NOT NULL CHECK(page_type IN ('standard', 'out_of_stock', 'discounted', 'multipack', 'membership')),
    html_snapshot TEXT NOT NULL, -- Captured product-page HTML used by parser tests
    expected_output TEXT NOT NULL, -- JSON object containing the expected ProductData fields
    captured_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')), -- UTC capture timestamp generated by SQLite
    is_stale INTEGER NOT NULL DEFAULT 0, -- Boolean integer; 1 excludes the sample from active golden tests
    created_by TEXT NOT NULL DEFAULT 'auto' CHECK(created_by IN ('coldstart', 'auto')) -- Provenance: reviewed cold start or automatic runtime seed
);

-- Signature-deduplicated terminal-failure tickets requiring human attention.
CREATE TABLE IF NOT EXISTS escalations (
    id INTEGER PRIMARY KEY AUTOINCREMENT, -- Surrogate escalation identifier; referenced by scrape_runs.escalation_id
    signature TEXT NOT NULL UNIQUE, -- Deduplication key whose first pipe-delimited segment must be the site
    reason TEXT NOT NULL CHECK(reason IN ('parser_broken', 'infra_failure', 'api_malformed', 'mass_invalid_target')), -- Closed failure category
    affected_count INTEGER NOT NULL DEFAULT 1, -- Number of executions merged into this ticket
    snapshot TEXT, -- Optional JSON diagnostic snapshot captured at escalation time
    status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open', 'resolved')), -- Human-resolution state: open or resolved
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -- UTC ticket creation timestamp generated by SQLite
);

-- One execution record for every terminal scraping outcome.
CREATE TABLE IF NOT EXISTS scrape_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT, -- Surrogate execution identifier; referenced by results.run_id
    url TEXT NOT NULL, -- Requested product URL
    host TEXT NOT NULL, -- Normalized URL host used for routing
    site TEXT NOT NULL, -- Retailer partition key resolved from the host
    scraper TEXT NOT NULL, -- Concrete scraper class or route used for this execution
    scraped_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')), -- UTC execution timestamp generated by SQLite
    outcome TEXT NOT NULL CHECK(outcome IN ('success', 'escalated', 'invalid_target')), -- Terminal outcome: success, escalated, or invalid_target
    -- Winning execution route; retried remains reserved but is not currently written.
    path TEXT NOT NULL CHECK(path IN ('fast', 'retried', 'agent_repaired', 'backup_1', 'backup_2', 'escalated', 'invalid_target')),
    winning_parser_id INTEGER REFERENCES parsers(id), -- Parser that produced a successful HTML extraction, when applicable
    attempts INTEGER NOT NULL DEFAULT 1, -- Reserved attempt counter; current writers leave the default value
    repair_model TEXT, -- Model identifier used when an agent-repaired parser won
    latency_ms INTEGER, -- End-to-end execution latency in milliseconds
    signature TEXT, -- Failure signature copied onto terminal failed executions
    error TEXT, -- Terminal diagnostic message for failed executions
    escalation_id INTEGER REFERENCES escalations(id) ON DELETE SET NULL -- Aggregate failure ticket linked to this execution
);

-- Append-only qualified ProductData results produced by successful executions.
CREATE TABLE IF NOT EXISTS results (
    id INTEGER PRIMARY KEY AUTOINCREMENT, -- Surrogate result identifier
    url TEXT NOT NULL, -- Product URL represented by the stored result
    site TEXT NOT NULL, -- Retailer key copied from ProductData.website
    scraped_at TEXT NOT NULL, -- UTC timestamp supplied with the qualified result
    product_data TEXT NOT NULL, -- Complete qualified ProductData serialized as JSON
    run_id INTEGER REFERENCES scrape_runs(id) ON DELETE SET NULL -- Exact producing execution when correlation is available
);

-- Site-specific phrases learned for cheap invalid-target pre-detection.
CREATE TABLE IF NOT EXISTS invalid_target_phrases (
    id INTEGER PRIMARY KEY AUTOINCREMENT, -- Surrogate learned-phrase identifier
    site TEXT NOT NULL, -- Retailer partition key
    phrase TEXT NOT NULL, -- Lower-level page phrase indicating a non-product target
    source TEXT NOT NULL DEFAULT 'agent_backfill', -- Provenance label for the learned phrase
    added_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) -- UTC insertion timestamp generated by SQLite
);

"""

_INDEX_DDL = """
-- Speeds URL history lookup in reverse chronological order.
CREATE INDEX IF NOT EXISTS idx_scrape_runs_url_scraped ON scrape_runs(url, scraped_at);
-- Supports per-site execution filtering and clearing.
CREATE INDEX IF NOT EXISTS idx_scrape_runs_site ON scrape_runs(site);
-- Supports per-site outcome analysis over time.
CREATE INDEX IF NOT EXISTS idx_scrape_runs_site_outcome ON scrape_runs(site, outcome, scraped_at);
-- Supports aggregate-ticket to execution correlation.
CREATE INDEX IF NOT EXISTS idx_scrape_runs_escalation ON scrape_runs(escalation_id);
-- Speeds product result history lookup by URL.
CREATE INDEX IF NOT EXISTS idx_results_url ON results(url);
-- Supports per-site result history in timestamp order.
CREATE INDEX IF NOT EXISTS idx_results_site_scraped ON results(site, scraped_at);
-- Supports execution to qualified-result correlation.
CREATE INDEX IF NOT EXISTS idx_results_run ON results(run_id);
-- Supports active parser selection within a site.
CREATE INDEX IF NOT EXISTS idx_parsers_site_status ON parsers(site, status);
-- Supports active golden coverage lookup by site and page type.
CREATE INDEX IF NOT EXISTS idx_golden_site_page ON golden_samples(site, page_type, is_stale);
-- Supports phrase matching and clearing within a site.
CREATE INDEX IF NOT EXISTS idx_phrases_site ON invalid_target_phrases(site);
"""

# Incremental columns. New databases get these from _DDL; init_db() adds them
# to historical databases automatically.
_ADDED_COLUMNS: dict[str, dict[str, str]] = {
    "golden_samples": {
        "created_by": (
            "TEXT NOT NULL DEFAULT 'auto' "
            "CHECK(created_by IN ('coldstart', 'auto'))"
        ),
    },
    "scrape_runs": {
        "signature": "TEXT",
        "error": "TEXT",
        "repair_model": "TEXT",
        "escalation_id": (
            "INTEGER REFERENCES escalations(id) ON DELETE SET NULL"
        ),
    },
    "results": {
        "run_id": "INTEGER REFERENCES scrape_runs(id) ON DELETE SET NULL",
    },
}

_RENAMED_COLUMNS: dict[str, dict[str, str]] = {
    "scrape_runs": {"model_used": "repair_model"},
}

_REMOVED_COLUMNS: dict[str, tuple[str, ...]] = {
    "scrape_runs": ("cost",),
}

CLEARABLE_TABLES = (
    "parsers",
    "golden_samples",
    "results",
    "escalations",
    "invalid_target_phrases",
    "scrape_runs",
)
DEFAULT_CLEAR_TABLES = ("parsers", "golden_samples")


class ScrapeDB:
    """SQLite connection manager for the scraping module's 6 tables."""

    def __init__(self, db_path: str | Path = "scraping.db"):
        self._db_path = str(db_path)
        self._conn: Optional[sqlite3.Connection] = None

    @property
    def conn(self) -> sqlite3.Connection:
        if self._conn is None:
            self._conn = sqlite3.connect(self._db_path)
            self._conn.row_factory = sqlite3.Row
            self._conn.execute("PRAGMA journal_mode=WAL")
            self._conn.execute("PRAGMA foreign_keys=ON")
        return self._conn

    def init_db(self) -> None:
        self.conn.executescript(_DDL)
        self._ensure_columns()
        self.conn.executescript(_INDEX_DDL)

    def _ensure_columns(self) -> None:
        """Idempotently apply additive, rename, and removal migrations."""
        migration_tables = (
            set(_ADDED_COLUMNS) | set(_RENAMED_COLUMNS) | set(_REMOVED_COLUMNS)
        )
        existing_by_table = {
            table: {
                row["name"]
                for row in self.conn.execute(f"PRAGMA table_info({table})")
            }
            for table in migration_tables
        }
        additions_done = all(
            columns.keys() <= existing_by_table[table]
            for table, columns in _ADDED_COLUMNS.items()
        )
        renames_done = all(
            old not in existing_by_table[table]
            and new in existing_by_table[table]
            for table, renames in _RENAMED_COLUMNS.items()
            for old, new in renames.items()
        )
        removals_done = all(
            column not in existing_by_table[table]
            for table, columns in _REMOVED_COLUMNS.items()
            for column in columns
        )
        if additions_done and renames_done and removals_done:
            return

        try:
            # Serialize the inspect-and-alter sequence so concurrent first starts
            # cannot both observe the same missing column.
            self.conn.execute("BEGIN IMMEDIATE")

            for table, renames in _RENAMED_COLUMNS.items():
                locked_existing = {
                    row["name"]
                    for row in self.conn.execute(f"PRAGMA table_info({table})")
                }
                for old, new in renames.items():
                    if old in locked_existing and new not in locked_existing:
                        self.conn.execute(
                            f"ALTER TABLE {table} RENAME COLUMN {old} TO {new}"
                        )
                        locked_existing.remove(old)
                        locked_existing.add(new)
                    elif old in locked_existing and new in locked_existing:
                        self.conn.execute(
                            f"UPDATE {table} SET {new} = COALESCE({new}, {old})"
                        )
                        self.conn.execute(
                            f"ALTER TABLE {table} DROP COLUMN {old}"
                        )
                        locked_existing.remove(old)

            for table, columns in _ADDED_COLUMNS.items():
                locked_existing = {
                    row["name"]
                    for row in self.conn.execute(f"PRAGMA table_info({table})")
                }
                for column, ddl in columns.items():
                    if column not in locked_existing:
                        self.conn.execute(
                            f"ALTER TABLE {table} ADD COLUMN {column} {ddl}"
                        )

            for table, columns in _REMOVED_COLUMNS.items():
                locked_existing = {
                    row["name"]
                    for row in self.conn.execute(f"PRAGMA table_info({table})")
                }
                for column in columns:
                    if column in locked_existing:
                        self.conn.execute(
                            f"ALTER TABLE {table} DROP COLUMN {column}"
                        )
            self.conn.commit()
        except Exception:
            self.conn.rollback()
            raise

    def clear_site(
        self,
        site: str,
        tables: Sequence[str] | None = None,
    ) -> dict[str, int]:
        """Hard-delete selected rows for *site* in one transaction.

        Omitting ``tables`` preserves the historical behavior: parsers and
        golden samples are deleted, while run-history rows are retained and
        any parser references on those rows are detached first.
        """
        if tables is None:
            selected = DEFAULT_CLEAR_TABLES
        elif isinstance(tables, str):
            selected = (tables,)
        else:
            selected = tuple(tables)
        unknown = [table for table in selected if table not in CLEARABLE_TABLES]
        if unknown:
            valid = ", ".join(CLEARABLE_TABLES)
            raise ValueError(
                f"Unknown clearable table(s): {unknown!r}. Valid tables: {valid}"
            )
        if not selected:
            return {}

        # Avoid executing the same DELETE twice if a caller repeats a table.
        selected = tuple(dict.fromkeys(selected))
        selected_set = set(selected)
        counts: dict[str, int] = {}
        self.conn.execute("BEGIN IMMEDIATE")
        try:
            if "scrape_runs" in selected_set:
                cur = self.conn.execute(
                    "UPDATE results SET run_id = NULL "
                    "WHERE run_id IN "
                    "(SELECT id FROM scrape_runs WHERE site = ?)",
                    (site,),
                )
                counts["results_detached"] = cur.rowcount
                cur = self.conn.execute(
                    "DELETE FROM scrape_runs WHERE site = ?", (site,)
                )
                counts["scrape_runs"] = cur.rowcount

            if "parsers" in selected_set:
                cur = self.conn.execute(
                    "UPDATE scrape_runs SET winning_parser_id = NULL "
                    "WHERE site = ? AND winning_parser_id IS NOT NULL",
                    (site,),
                )
                counts["scrape_runs_detached"] = cur.rowcount
                cur = self.conn.execute(
                    "DELETE FROM parsers WHERE site = ?", (site,)
                )
                counts["parsers"] = cur.rowcount

            for table in (
                "golden_samples",
                "results",
                "invalid_target_phrases",
            ):
                if table in selected_set:
                    cur = self.conn.execute(
                        f"DELETE FROM {table} WHERE site = ?", (site,)
                    )
                    counts[table] = cur.rowcount

            if "escalations" in selected_set:
                cur = self.conn.execute(
                    "UPDATE scrape_runs SET escalation_id = NULL "
                    "WHERE escalation_id IN ("
                    "SELECT id FROM escalations "
                    "WHERE substr(signature, 1, "
                    "instr(signature || '|', '|') - 1) = ?)",
                    (site,),
                )
                counts["scrape_runs_escalation_detached"] = cur.rowcount
                cur = self.conn.execute(
                    "DELETE FROM escalations "
                    "WHERE substr(signature, 1, "
                    "instr(signature || '|', '|') - 1) = ?",
                    (site,),
                )
                counts["escalations"] = cur.rowcount

            self.conn.commit()
            return counts
        except Exception:
            self.conn.rollback()
            raise

    def close(self) -> None:
        if self._conn is not None:
            self._conn.close()
            self._conn = None

    def __enter__(self) -> ScrapeDB:
        self.init_db()
        return self

    def __exit__(self, *args) -> None:
        self.close()
